version: "3.8"

services:
  server:
    build:
      context: .
    image: titoboyet/factoryded:latest
    volumes:
      - ./data:/home/steam/satisfactory
    ports:
      - 15000:15000/udp
      - 7777:7777/udp
      - 5555:15777/udp

volumes:
  data:
